# Generated by Django 2.2.6 on 2019-10-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='room_photos')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_link', models.CharField(max_length=300)),
                ('img_link', models.CharField(max_length=300)),
                ('img_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Image')),
            ],
        ),
    ]
