# Generated by Django 2.2.6 on 2019-10-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='img_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='img_path',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.Image'),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='web_link',
            field=models.URLField(),
        ),
    ]
