# Generated by Django 2.2.5 on 2019-10-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('edges', models.ManyToManyField(blank=True, related_name='src', to='crawler.Edge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uri', models.URLField(primary_key=True, serialize=False)),
                ('keywords', models.ManyToManyField(blank=True, related_name='image', to='crawler.Keyword')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='crawler.Node')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge', to='crawler.Node'),
        ),
    ]
